// <auto-generated />
using System;
using BlazorVentas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorVentas.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    partial class CommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorVentas.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.ClaseCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ClaseClientes");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Cobrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cobradores");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoClientes");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.TipoEnvase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoEnvases");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BultosXCamada")
                        .HasColumnType("int");

                    b.Property<int?>("BultosXPalet")
                        .HasColumnType("int");

                    b.Property<int>("CodigoArticulo")
                        .HasColumnType("int");

                    b.Property<int>("CodigoParaMostrar")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<long?>("DUN14")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long?>("EAUN13")
                        .HasColumnType("bigint");

                    b.Property<bool>("Inhabilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("MensajeSobreArticulo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrigenId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoBulto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PesoEscurrido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PesoNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PesoPalet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoBultoAlto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoBultoAncho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoBultoProfundo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoPaletAlto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoPaletAncho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoPaletProfundo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoUnidadAlto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoUnidadAncho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TamañoUnidadProfundo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoEnvaseId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadXBulto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("TipoEnvaseId");

                    b.HasIndex("CompanyId", "CodigoArticulo")
                        .IsUnique();

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CP")
                        .HasColumnType("int");

                    b.Property<string>("CUIT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ClaseClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("CobradorId")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoDescuentoId")
                        .HasColumnType("int");

                    b.Property<int>("CodigoParaMostrar")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CondicionPago")
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DomicilioEntrega")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DomicilioLegal")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaCompra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inhabilitado")
                        .HasColumnType("bit");

                    b.Property<int>("ListaPrecio")
                        .HasColumnType("int");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MensajeSobreCliente")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NumeroProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.Property<string>("Web")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseClienteId");

                    b.HasIndex("CobradorId");

                    b.HasIndex("CodigoDescuentoId");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("TipoClienteId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("ZonaId");

                    b.HasIndex("CompanyId", "CodigoCliente", "CodigoSucursal")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ClientePrecio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPromocion")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClientePrecios");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImpuestoNacional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpuestoProvincial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ComprobanteId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.VentaLinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpuestoNacional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpuestoProvincial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaLineas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Localidad", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.ABM.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Articulo", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.Company", "Company")
                        .WithMany("Articulos")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.ABM.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.Pais", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.TipoEnvase", "TipoEnvase")
                        .WithMany()
                        .HasForeignKey("TipoEnvaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Marca");

                    b.Navigation("Origen");

                    b.Navigation("TipoEnvase");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Cliente", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.ABM.ClaseCliente", "ClaseCliente")
                        .WithMany()
                        .HasForeignKey("ClaseClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.Cobrador", "Cobrador")
                        .WithMany()
                        .HasForeignKey("CobradorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.Descuento", "CodigoDescuento")
                        .WithMany()
                        .HasForeignKey("CodigoDescuentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.Company", "Company")
                        .WithMany("Clientes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.ABM.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorVentas.Data.Models.ABM.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClaseCliente");

                    b.Navigation("Cobrador");

                    b.Navigation("CodigoDescuento");

                    b.Navigation("Company");

                    b.Navigation("Localidad");

                    b.Navigation("Provincia");

                    b.Navigation("TipoCliente");

                    b.Navigation("Vendedor");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ClientePrecio", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.Articulo", "Articulo")
                        .WithMany("PreciosEspeciales")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.Cliente", "Cliente")
                        .WithMany("PreciosEspeciales")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Venta", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.Company", "Company")
                        .WithMany("Ventas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.Comprobante", "Comprobante")
                        .WithMany("Ventas")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.Vendedor", "Vendedor")
                        .WithMany("Ventas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Company");

                    b.Navigation("Comprobante");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.VentaLinea", b =>
                {
                    b.HasOne("BlazorVentas.Data.Models.Articulo", "Articulo")
                        .WithMany("VentasLineas")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorVentas.Data.Models.Venta", "Venta")
                        .WithMany("Lineas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.ABM.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Articulo", b =>
                {
                    b.Navigation("PreciosEspeciales");

                    b.Navigation("VentasLineas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Cliente", b =>
                {
                    b.Navigation("PreciosEspeciales");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Company", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Clientes");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Comprobante", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Vendedor", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BlazorVentas.Data.Models.Venta", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
